### ISSUE TITLE
为什么一样的问题，机器人使用API回答，跟在chat.openAI的网页回答会不一样

### ISSUE THREAD

**Issue by ChokWah** [sytpb/chatgpt-wework-robot#4]
为什么一样的问题，机器人使用API回答，跟在chat.openAI的网页回答会不一样？
而且机器人貌似无法理解上下文

**Comment by sytpb** [comment]
1、同一问题，网页上有时回答也有区别，不是每个问题都是固定回答，那就不是AI了，另外现在API接入的是3.5-turbo , 不是gpt 4 或者3，3.5-turbo是资费最低的接口，如果想要和网页一样的效果，可以配置成gpt4 或者gpt3 （这个还未验证过）. 

2、无法理解上下文这个确实是个问题，还需要测试验证一下。

查了下gpt 社区这样说的
it is because the completions endpoint has been trained on Davinci Instruct (text-davinci-002, GPT-3 vintage), not the recent ChatGPT model, which is using a more recent GPT model (3.5) and which has been optimised in a different manner,

关于与网页回答不一样
https://community.openai.com/t/chatgpt-completions-api-doesnt-reply-as-the-web-chat-playground-does/23655

关于记不住会话上下文
https://community.openai.com/t/chatgpt-api-is-not-able-to-remember-conversation/82273/5
https://cobusgreyling.medium.com/when-using-the-chatgpt-api-users-will-have-to-manage-the-context-ba5869238913
